apiVersion: apps/v1
kind: Deployment
metadata:
  name: pair-selector
  namespace: {{ .Release.Namespace }}
  labels:
    app: pair-selector
spec:
  replicas: {{ .Values.pairSelector.deployment.replicas }}
  selector:
    matchLabels:
      app: pair-selector
  template:
    metadata:
      labels:
        app: pair-selector
    spec:
      containers:
      - name: pair-selector
        image: "{{ .Values.registry }}/{{ .Values.app }}/{{ .Values.pairSelector.image.name }}:{{ .Values.pairSelector.image.tag }}"
        imagePullPolicy: {{ .Values.pairSelector.image.pullPolicy }}
        env:
        - name: KUCOIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-key
        - name: KUCOIN_API_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-secret
        - name: KUCOIN_API_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-passphrase
        {{- range .Values.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.pairSelector.envVars }}
        {{- range .Values.pairSelector.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.secretEnvVars }}
        {{- range .Values.secretEnvVars }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8082 # Assuming health check on port 8082 for pair-selector
          name: http-health
        resources:
          requests:
            cpu: {{ .Values.pairSelector.resources.requests.cpu }}
            memory: {{ .Values.pairSelector.resources.requests.memory }}
          limits:
            cpu: {{ .Values.pairSelector.resources.limits.cpu }}
            memory: {{ .Values.pairSelector.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-health # Reference the port name
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-health # Reference the port name
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
