apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: trading-engine
spec:
  replicas: {{ .Values.tradingEngine.deployment.replicas }}
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
    spec:
      containers:
      - name: trading-engine
        image: "{{ .Values.registry }}/{{ .Values.app }}/{{ .Values.tradingEngine.image.name }}:{{ .Values.tradingEngine.image.tag }}"
        imagePullPolicy: {{ .Values.tradingEngine.image.pullPolicy }}
        env:
        - name: KUCOIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-key
        - name: KUCOIN_API_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-secret
        - name: KUCOIN_API_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kucoinApiSecretName | default "kucoin-api-credentials" }}
              key: api-passphrase
        {{- range .Values.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.tradingEngine.envVars }}
        {{- range .Values.tradingEngine.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.secretEnvVars }}
        {{- range .Values.secretEnvVars }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8083 # Assuming health check on port 8083 for trading-engine
          name: http-health
        resources:
          requests:
            cpu: {{ .Values.tradingEngine.resources.requests.cpu }}
            memory: {{ .Values.tradingEngine.resources.requests.memory }}
          limits:
            cpu: {{ .Values.tradingEngine.resources.limits.cpu }}
            memory: {{ .Values.tradingEngine.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-health # Reference the port name
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-health # Reference the port name
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
