registry: 929572853995.dkr.ecr.eu-west-1.amazonaws.com
app: crypto-trading-bot-v4

# Kucoin API credentials are now managed via a Kubernetes secret.
# Define the name of the secret in this values file.
# See helm/README.md for instructions on creating this secret.
kucoinApiSecretName: "kucoin-api-credentials"

# markets:
#   kucoin:
#     apiKey: "" # DEPRECATED: Managed by kucoinApiSecretName
#     apiSecret: "" # DEPRECATED: Managed by kucoinApiSecretName
#     apiPassphrase: "" # DEPRECATED: Managed by kucoinApiSecretName

envVars:
  - name: LOG_LEVEL
    value: info
secretEnvVars:
  - name: DB_URI
    secretName: crypto-trading-pguser-postgres
    secretKey: uri
pairSelector:
  image:
    name: pair-selector # Renamed from repository to match existing structure
    tag: 0.1.0
    pullPolicy: IfNotPresent
  deployment: # Kept deployment.replicas as it was, assuming it's service specific
    replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  envVars:
    - name: EVALUATION_INTERVAL_HOURS
      value: "3"
    - name: MIN_VOLUME_USDT
      value: "1000000"
    - name: MAX_ACTIVE_PAIRS
      value: "10"
priceCollector:
  image:
    name: price-collector # Renamed from repository to match existing structure
    tag: 0.1.0
    pullPolicy: IfNotPresent
  deployment: # Kept deployment.replicas as it was
    replicas: 1
  resources:
    requests:
      cpu: "150m" # Example: different values for price collector
      memory: "192Mi"
    limits:
      cpu: "300m"
      memory: "384Mi"
  envVars:
    - name: COLLECTION_INTERVAL_SECONDS
      value: "60"
    - name: BATCH_SIZE
      value: "1000"
tradingEngine:
  image:
    name: trading-engine # Renamed from repository to match existing structure
    tag: 0.1.0
    pullPolicy: IfNotPresent
  deployment: # Kept deployment.replicas as it was
    replicas: 1
  resources:
    requests:
      cpu: "120m" # Example: different values for trading engine
      memory: "160Mi"
    limits:
      cpu: "250m"
      memory: "320Mi"
  envVars:
    - name: TRADING_INTERVAL_SECONDS
      value: "60"
    - name: DEFAULT_POSITION_SIZE_USDT
      value: "10"
    - name: KUCOIN_SANDBOX
      value: "true"
